apiVersion: cert-manager.io/v1

kind: Certificate

metadata: 
  name: conhecimentoti-tls-padua

spec:
  commonName: conhecimentoti.padua.iff.edu.br
  secretName: cer-conhecimentoti-padua
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  
  dnsNames:
    - conhecimentoti.padua.iff.edu.br