apiVersion: v1

kind: Service

metadata:
  name: service-conhecimentoti-padua

spec:
  selector:
    app: app-conhecimentoti-padua

  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort 

